### ISSUE TITLE
Inadequate documentation - UI does not show

### ISSUE THREAD

**Issue by ssmails** [verdverm/dgraph-ratel#1]
After cloning and doing
1. yarn install
2. yarn
3. yarn watch

Several Errors seen.
And I don't see anything at http://localhost:3000/

[dgraph-ratel-errors.zip](https://github.com/verdverm/dgraph-ratel/files/2412937/dgraph-ratel-errors.zip)

**Comment by wangdejun** [comment]
please show the errors in detail

**Comment by ssmails** [comment]
The errors are part of the zip file dgraph-ratel-errors.zip attached above

**Comment by verdverm** [comment]
@ssmails   This is an unmaintained repository for a fun little experiment. I am unable to put any time into it at this point and do not foresee myself touching it again.

By the way, would never ever download a zip and unpack it from an untrusted source, super bad security. Please post errors as text. use the "```" to make code and terminal output readable.
